---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: plone
spec:
  rules:
  - host: plone.REPLACE_ME_INGRESS_IP.nip.io
    http:
      paths:
      - backend:
          serviceName: plone
          servicePort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: plone
spec:
  selector:
    app: plone
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: plone
  labels:
    app: plone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plone
  template:
    metadata:
      labels:
        app: plone
    spec:
      containers:
      - name: plone
        image: plone:5.2.1-alpine
        ports:
        - containerPort: 8080
